#!/bin/bash
pip install -i https://test.pypi.org/simple/ widget-periodictable
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter nbextension      enable --py --sys-prefix appmode
jupyter serverextension  enable --py --sys-prefix appmode
jupyter nbextension      enable --py widgetsnbextension
